# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 851)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1130, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.img1_active = QtWidgets.QRadioButton(self.centralwidget)
        self.img1_active.setText("")
        self.img1_active.setObjectName("img1_active")
        self.horizontalLayout_3.addWidget(self.img1_active)
        self.img1_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.img1_label.setFont(font)
        self.img1_label.setObjectName("img1_label")
        self.horizontalLayout_3.addWidget(self.img1_label)
        self.components_img1 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.components_img1.setFont(font)
        self.components_img1.setObjectName("components_img1")
        self.components_img1.addItem("")
        self.components_img1.addItem("")
        self.components_img1.addItem("")
        self.components_img1.addItem("")
        self.components_img1.addItem("")
        self.horizontalLayout_3.addWidget(self.components_img1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1.sizePolicy().hasHeightForWidth())
        self.img1.setSizePolicy(sizePolicy)
        self.img1.setText("")
        self.img1.setObjectName("img1")
        self.horizontalLayout_2.addWidget(self.img1)
        self.img1_modified = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1_modified.sizePolicy().hasHeightForWidth())
        self.img1_modified.setSizePolicy(sizePolicy)
        self.img1_modified.setText("")
        self.img1_modified.setObjectName("img1_modified")
        self.horizontalLayout_2.addWidget(self.img1_modified)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 4)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.output_choice = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.output_choice.setFont(font)
        self.output_choice.setObjectName("output_choice")
        self.output_choice.addItem("")
        self.output_choice.addItem("")
        self.output_choice.addItem("")
        self.horizontalLayout_12.addWidget(self.output_choice)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.choose_comp1 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.choose_comp1.setFont(font)
        self.choose_comp1.setObjectName("choose_comp1")
        self.choose_comp1.addItem("")
        self.choose_comp1.addItem("")
        self.choose_comp1.addItem("")
        self.horizontalLayout_13.addWidget(self.choose_comp1)
        self.percentage1 = QtWidgets.QSlider(self.centralwidget)
        self.percentage1.setOrientation(QtCore.Qt.Horizontal)
        self.percentage1.setObjectName("percentage1")
        self.horizontalLayout_13.addWidget(self.percentage1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_9.addLayout(self.verticalLayout_12)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_14.addLayout(self.horizontalLayout_16)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.comp1_effect = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.comp1_effect.setFont(font)
        self.comp1_effect.setObjectName("comp1_effect")
        self.comp1_effect.addItem("")
        self.comp1_effect.addItem("")
        self.comp1_effect.addItem("")
        self.comp1_effect.addItem("")
        self.comp1_effect.addItem("")
        self.comp1_effect.addItem("")
        self.comp1_effect.addItem("")
        self.verticalLayout_13.addWidget(self.comp1_effect)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_19.addWidget(self.label_9)
        self.choose_comp2 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.choose_comp2.setFont(font)
        self.choose_comp2.setObjectName("choose_comp2")
        self.choose_comp2.addItem("")
        self.choose_comp2.addItem("")
        self.choose_comp2.addItem("")
        self.horizontalLayout_19.addWidget(self.choose_comp2)
        self.percentage2 = QtWidgets.QSlider(self.centralwidget)
        self.percentage2.setOrientation(QtCore.Qt.Horizontal)
        self.percentage2.setObjectName("percentage2")
        self.horizontalLayout_19.addWidget(self.percentage2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.verticalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.comp2_effect = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.comp2_effect.setFont(font)
        self.comp2_effect.setObjectName("comp2_effect")
        self.comp2_effect.addItem("")
        self.comp2_effect.addItem("")
        self.comp2_effect.addItem("")
        self.comp2_effect.addItem("")
        self.comp2_effect.addItem("")
        self.comp2_effect.addItem("")
        self.comp2_effect.addItem("")
        self.verticalLayout_16.addWidget(self.comp2_effect)
        self.horizontalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.verticalLayout_8.addLayout(self.verticalLayout_15)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.img2_active = QtWidgets.QRadioButton(self.centralwidget)
        self.img2_active.setText("")
        self.img2_active.setObjectName("img2_active")
        self.horizontalLayout_5.addWidget(self.img2_active)
        self.img2_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.img2_label.setFont(font)
        self.img2_label.setObjectName("img2_label")
        self.horizontalLayout_5.addWidget(self.img2_label)
        self.components_img2 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.components_img2.setFont(font)
        self.components_img2.setObjectName("components_img2")
        self.components_img2.addItem("")
        self.components_img2.addItem("")
        self.components_img2.addItem("")
        self.components_img2.addItem("")
        self.components_img2.addItem("")
        self.horizontalLayout_5.addWidget(self.components_img2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.img2 = QtWidgets.QLabel(self.centralwidget)
        self.img2.setText("")
        self.img2.setObjectName("img2")
        self.horizontalLayout_6.addWidget(self.img2)
        self.img2_modified = QtWidgets.QLabel(self.centralwidget)
        self.img2_modified.setText("")
        self.img2_modified.setObjectName("img2_modified")
        self.horizontalLayout_6.addWidget(self.img2_modified)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 4)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.output1label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.output1label.setFont(font)
        self.output1label.setObjectName("output1label")
        self.horizontalLayout_11.addWidget(self.output1label)
        self.output2label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.output2label.setFont(font)
        self.output2label.setObjectName("output2label")
        self.horizontalLayout_11.addWidget(self.output2label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.output1 = QtWidgets.QLabel(self.centralwidget)
        self.output1.setText("")
        self.output1.setObjectName("output1")
        self.horizontalLayout_7.addWidget(self.output1)
        self.output2 = QtWidgets.QLabel(self.centralwidget)
        self.output2.setText("")
        self.output2.setObjectName("output2")
        self.horizontalLayout_7.addWidget(self.output2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_image = QtWidgets.QAction(MainWindow)
        self.actionOpen_image.setObjectName("actionOpen_image")
        self.actionOpen_Image2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image2.setObjectName("actionOpen_Image2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Display"))
        self.img1_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; font-style:italic;\">Image1</span></p></body></html>"))
        self.components_img1.setItemText(0, _translate("MainWindow", "Components"))
        self.components_img1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.components_img1.setItemText(2, _translate("MainWindow", "Phase"))
        self.components_img1.setItemText(3, _translate("MainWindow", "Real"))
        self.components_img1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.label_7.setText(_translate("MainWindow", "Mixer Output to :"))
        self.output_choice.setItemText(0, _translate("MainWindow", "Output"))
        self.output_choice.setItemText(1, _translate("MainWindow", "Output1"))
        self.output_choice.setItemText(2, _translate("MainWindow", "Output2"))
        self.label_8.setText(_translate("MainWindow", "Component 1 :"))
        self.choose_comp1.setItemText(0, _translate("MainWindow", "Image"))
        self.choose_comp1.setItemText(1, _translate("MainWindow", "Image1"))
        self.choose_comp1.setItemText(2, _translate("MainWindow", "Image2"))
        self.comp1_effect.setItemText(0, _translate("MainWindow", "Effect"))
        self.comp1_effect.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.comp1_effect.setItemText(2, _translate("MainWindow", "Phase"))
        self.comp1_effect.setItemText(3, _translate("MainWindow", "Uniphase"))
        self.comp1_effect.setItemText(4, _translate("MainWindow", "Real"))
        self.comp1_effect.setItemText(5, _translate("MainWindow", "Imaginary"))
        self.comp1_effect.setItemText(6, _translate("MainWindow", "Unimagnitude"))
        self.label_9.setText(_translate("MainWindow", "Component 2 :"))
        self.choose_comp2.setItemText(0, _translate("MainWindow", "Image"))
        self.choose_comp2.setItemText(1, _translate("MainWindow", "Image1"))
        self.choose_comp2.setItemText(2, _translate("MainWindow", "Image2"))
        self.comp2_effect.setItemText(0, _translate("MainWindow", "Effect"))
        self.comp2_effect.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.comp2_effect.setItemText(2, _translate("MainWindow", "Phase"))
        self.comp2_effect.setItemText(3, _translate("MainWindow", "Uniphase"))
        self.comp2_effect.setItemText(4, _translate("MainWindow", "Real"))
        self.comp2_effect.setItemText(5, _translate("MainWindow", "Imaginary"))
        self.comp2_effect.setItemText(6, _translate("MainWindow", "Unimagnitude"))
        self.img2_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; font-style:italic;\">Image2</span></p></body></html>"))
        self.components_img2.setItemText(0, _translate("MainWindow", "Components"))
        self.components_img2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.components_img2.setItemText(2, _translate("MainWindow", "Phase"))
        self.components_img2.setItemText(3, _translate("MainWindow", "Real"))
        self.components_img2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.output1label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">OUTPUT1</span></p></body></html>"))
        self.output2label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">OUTPUT2</span></p></body></html>"))
        self.actionOpen_image.setText(_translate("MainWindow", "Open"))
        self.actionOpen_Image2.setText(_translate("MainWindow", "Open Image2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

